import Mathlib

/-!
# Challenge: quantum soundness of the Pauli basis test

Self-contained comparator challenge for `MIPStarRE.QPBT.pauli_soundness` and
`MIPStarRE.QPBT.pauli_soundness_qubit`, the source statements of `thm:pauli`
and `cor:pauli-binary` — the quantum soundness of the Pauli basis test
(Natarajan, Wright, "NEEXP in MIP*", and the low-degree chapter of the
quantum low individual degree test literature), the ingredient that turns the
classical low-degree test into a Pauli-braiding-style rigidity statement.

This file imports **only Mathlib** and re-declares, verbatim and in dependency
order, every definition in the transitive closure of the statements of the two
theorems; the theorems themselves are stated with `sorry`.  It is the entire
human audit surface: a reader who agrees that this file states the intended
theorems does not need to read anything else.  The
[comparator](https://github.com/leanprover/comparator) tool verifies
mechanically that the [MIPStarRE](https://github.com/LionSR/MIPStarRE)
library declares statements identical to these and proves the theorems using
no axioms beyond `propext`, `Quot.sound`, and `Classical.choice`.

Each declaration carries a provenance comment (`-- source: <file>:<lines>`)
pointing at its origin in the MIPStarRE library, where docstrings cite the
paper passages being encoded.  This file is generated by
`scripts/comparator/` in that repository; see the README alongside this file
for how to run the verification.
-/

open scoped BigOperators MatrixOrder Matrix ComplexOrder
