import Mathlib

/-!
# Challenge: <the headline theorem of this project>

Template header for the comparator challenge of this repository's default
track.  Replace the prose below with this project's own once the headline
theorem exists; keep the shape, because it is what a reviewer reads first.
Everything from `import Mathlib` down to the `open` line at the bottom is
copied verbatim into the generated challenge file, so this file must elaborate
against Mathlib alone.

Self-contained comparator challenge for `<Root>.<Track>.mainFormal`, the source
statement of `<blueprint label>` in `<the paper, arXiv:XXXX.XXXXX>`.

This file imports **only Mathlib** and re-declares, verbatim and in dependency
order, every definition in the transitive closure of the statement of
`mainFormal`; the theorem itself is stated with `sorry`.  It is the entire
human audit surface: a reader who agrees that this file states the intended
theorem does not need to read anything else.  The
[comparator](https://github.com/leanprover/comparator) tool verifies
mechanically that this library declares statements identical to these and
proves the theorem using no axioms beyond `propext`, `Quot.sound`, and
`Classical.choice`.

Each declaration carries a provenance comment (`-- source: <file>:<lines>`)
pointing at its origin in the library, where docstrings cite the paper passages
being encoded.  This file is generated by `scripts/comparator/`; see the README
alongside this file for how to run the verification.
-/

-- Scoped notation the statement needs.  Add what this project's statement uses
-- and remove what it does not; an unused `open scoped` is harmless, a missing
-- one stops the generated file from elaborating.
open scoped BigOperators
