import Mathlib

/-!
# Challenge: the quantum Pauli basis test

Self-contained comparator challenge for the Pauli basis test results of
`MIPStarRE.QPBT` — `pauli_soundness`, its qubit form `pauli_soundness_qubit`,
and the completeness statement `exists_spcc_value_one`.

This file imports **only Mathlib** and re-declares, verbatim and in dependency
order, every definition in the transitive closure of those statements; the
theorems themselves are stated with `sorry`.  It is the entire human audit
surface: a reader who agrees that this file states the intended theorems does
not need to read anything else.  The
[comparator](https://github.com/leanprover/comparator) tool verifies
mechanically that the [MIPStarRE](https://github.com/LionSR/MIPStarRE)
library declares statements identical to these and proves the theorems using
no axioms beyond `propext`, `Quot.sound`, and `Classical.choice`.

Each declaration carries a provenance comment (`-- source: <file>:<lines>`)
pointing at its origin in the MIPStarRE library, where docstrings cite the
paper passages being encoded.  This file is generated by
`scripts/comparator/` in that repository; see the README alongside this file
for how to run the verification.
-/

open scoped BigOperators MatrixOrder Matrix ComplexOrder
