#!/usr/bin/env python3
"""Regression tests for comparator challenge drift checking."""

from __future__ import annotations

import importlib.util
import json
import sys
import tempfile
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "comparator" / "check_challenge_drift.py"
PR_CI = REPO_ROOT / ".github" / "workflows" / "pr-ci.yml"
README = REPO_ROOT / "scripts" / "comparator" / "README.md"

CHALLENGES_SCRIPT = REPO_ROOT / "scripts" / "comparator" / "challenges.py"
EXTRACTOR = REPO_ROOT / "scripts" / "comparator" / "extract_closure.lean"

_spec = importlib.util.spec_from_file_location("check_challenge_drift", SCRIPT)
assert _spec is not None and _spec.loader is not None
check_challenge_drift = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(check_challenge_drift)

_cspec = importlib.util.spec_from_file_location("challenges", CHALLENGES_SCRIPT)
assert _cspec is not None and _cspec.loader is not None
challenges = importlib.util.module_from_spec(_cspec)
_cspec.loader.exec_module(challenges)


class ComparatorChallengeDriftTests(unittest.TestCase):
    def test_clean_closure_rows_keeps_only_four_column_tsv_rows(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            raw = root / "closure.tsv"
            clean = root / "closure.clean.tsv"
            raw.write_text(
                "\n".join(
                    [
                        "noise from an unexpected diagnostic",
                        "Decl\tPaperLib/Foo.lean\t1\t2",
                        "too\tmany\tcolumns\tfor\tthis\trow",
                        "Generated\tPaperLib/Bar.lean\tNORANGE\tNORANGE",
                    ]
                )
                + "\n",
                encoding="utf-8",
            )

            check_challenge_drift.clean_closure_rows(raw, clean)

            self.assertEqual(
                clean.read_text(encoding="utf-8"),
                "Decl\tPaperLib/Foo.lean\t1\t2\n"
                "Generated\tPaperLib/Bar.lean\tNORANGE\tNORANGE\n",
            )

    def test_pr_ci_runs_drift_guard_after_lean_build_for_comparator_changes(self) -> None:
        workflow = PR_CI.read_text(encoding="utf-8")
        self.assertIn("comparator: ${{ steps.filter.outputs.comparator }}", workflow)
        self.assertIn("- 'scripts/comparator/**'", workflow)
        self.assertIn("needs.changes.outputs.comparator == 'true'", workflow)
        build = workflow.index("lake build")
        guard = workflow.index("python3 scripts/comparator/check_challenge_drift.py --root .")
        self.assertLess(build, guard)

    def test_pr_ci_checks_every_configured_challenge_without_naming_one(self) -> None:
        """With no `--challenge`, the guard walks the whole registry.

        Naming challenges in the workflow would mean editing CI whenever a
        track is added, and would break a repository whose tracks differ.
        """
        workflow = PR_CI.read_text(encoding="utf-8")
        self.assertIn(
            "python3 scripts/comparator/check_challenge_drift.py --root .", workflow
        )
        self.assertNotIn("check_challenge_drift.py --root . --challenge", workflow)

    def test_readme_documents_update_command_and_footer_source(self) -> None:
        readme = README.read_text(encoding="utf-8")
        self.assertIn("python3 scripts/comparator/check_challenge_drift.py --root . --update", readme)
        self.assertIn("challenge_footer.lean", readme)
        self.assertIn("local/project.json", readme)

    def test_every_challenge_is_configured_completely(self) -> None:
        """Whatever the project registers must be generatable as it stands."""
        for name, challenge in challenges.CHALLENGES.items():
            with self.subTest(challenge=name):
                self.assertEqual(challenge.name, name)
                self.assertTrue(challenge.targets)
                for path in (challenge.header, challenge.footer):
                    self.assertTrue(
                        (REPO_ROOT / path).is_file(), f"{name}: missing {path}"
                    )
                # The expected copy is generated by `--update`, so it may not
                # exist yet; its place in the tree is fixed all the same.
                self.assertTrue(
                    str(challenge.expected).startswith("scripts/comparator/expected/"),
                    f"{name}: {challenge.expected} is outside the expected/ directory",
                )
                self.assertEqual(
                    challenge.target_env, " ".join(challenge.targets)
                )

    def test_a_track_with_headline_theorems_becomes_a_challenge(self) -> None:
        """The registry is derived from `local/project.json`, not hand-written."""
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            (root / "local").mkdir()
            (root / "local/project.json").write_text(
                json.dumps(
                    {
                        "schema": 1,
                        "project": {"name": "Widget", "lean_root": "Widget", "track": "core"},
                        "tracks": {
                            "core": {
                                "headline": [["Widget.Core.main", "thm:main"]],
                                "expected_challenge": "scripts/comparator/expected/C.expected",
                            },
                            "extra": {"headline": [["Widget.Extra.other", "thm:other"]]},
                            "prose": {},
                        },
                    }
                ),
                encoding="utf-8",
            )
            registry = challenges.load_challenges(root)
            # A track without headline theorems has nothing to challenge.
            self.assertEqual(sorted(registry), ["core", "extra"])
            core = registry["core"]
            self.assertEqual(core.targets, ("Widget.Core.main",))
            self.assertEqual(core.target_env, "Widget.Core.main")
            self.assertEqual(
                core.expected, Path("scripts/comparator/expected/C.expected")
            )
            # The default track owns the unprefixed header/footer pair.
            self.assertEqual(
                core.header, Path("scripts/comparator/challenge_header.lean")
            )
            self.assertEqual(
                registry["extra"].footer,
                Path("scripts/comparator/challenge_extra_footer.lean"),
            )

    def test_a_repository_without_tracks_has_no_challenge(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            self.assertEqual(challenges.load_challenges(Path(td)), {})

    def test_the_shipped_footer_keeps_the_intentional_sorry_shape(self) -> None:
        """`generate_badges.py` subtracts exactly this hole from the count."""
        sys.path.insert(0, str(REPO_ROOT / "scripts"))
        import generate_badges

        footer = REPO_ROOT / "scripts/comparator/challenge_footer.lean"
        source = generate_badges.strip_comments_and_strings(
            footer.read_text(encoding="utf-8")
        )
        self.assertTrue(
            generate_badges.main_formal_has_intentional_sorry(source),
            "the challenge footer no longer ends with `theorem mainFormal ... "
            ":= by` / `sorry`",
        )

    def test_extractor_reads_targets_from_the_environment(self) -> None:
        extractor = EXTRACTOR.read_text(encoding="utf-8")
        self.assertIn("COMPARATOR_TARGETS", extractor)

    def test_the_drift_check_passes_when_no_challenge_is_configured(self) -> None:
        """A freshly bootstrapped repository must not fail its own CI step."""
        if challenges.CHALLENGES:
            self.skipTest("this repository configures a challenge")
        with tempfile.TemporaryDirectory() as td:
            self.assertEqual(check_challenge_drift.main(["--root", td]), 0)


if __name__ == "__main__":
    unittest.main()
