import Mathlib
import MIPStarRE.QPBT.Algebra.Subspaces
import MIPStarRE.QPBT.Algebra.Lines
import MIPStarRE.LDT.Basic.DistributionUniform

/-!
# Conditionally linear functions and graph distributions

The question distributions in the Pauli basis test are generated by a finite
graph of types and a shared seed, with each type applying a conditionally linear
map to that seed.  The inductive predicate below records the level structure
needed by later formalization stages.

## References

The source-facing nodes are `def:cl-func`, `def:cl-dist`, `lem:cl-concat`, and
`def:graph-distribution` in `blueprint/src/chapter/ch12_qpbt_games.tex:441-535`.
The paper origin is `references/qpbt-paper/05_conditionally_linear_functions.tex:35-57`
and `references/qpbt-paper/08_classical_and_quantum_low_degree_tests.tex:964-1010`.
-/

open scoped BigOperators

namespace MIPStarRE.QPBT

open MIPStarRE.LDT

variable {K ι : Type*} [Field K] [Fintype ι] [DecidableEq ι]

/--
The source definition is recursive in the residual map.  A direct inductive
predicate with that recursive occurrence under a dependent finite-set index is
rejected by Lean's strict-positivity checker.  We therefore expose the same
public predicate through a positive syntax tree (`CondLinearTerm`), together
with its support invariant and evaluation function.  This is a representation
deviation forced by Lean, not an additional mathematical hypothesis.  It encodes
`def:cl-func`, blueprint `blueprint/src/chapter/ch12_qpbt_games.tex:441-463`,
paper origin `references/qpbt-paper/05_conditionally_linear_functions.tex:35-57`.
-/
inductive CondLinearTerm (K : Type*) [Field K] {ι : Type*} [Fintype ι]
    [DecidableEq ι] : ℕ → Type _ where
  | zero : CondLinearTerm K (ι := ι) 0
  | succ {ell : ℕ}
      (S₁ : Finset ι)
      (L₁ : (ι → K) →ₗ[K] (ι → K))
      (hSupport : ∀ x i, i ∉ S₁ → L₁ x i = 0)
      (rest : (ι → K) → CondLinearTerm K (ι := ι) ell) :
      CondLinearTerm K (ι := ι) (ell + 1)

/-- Restrict a coordinate vector to a register, zeroing the complementary
coordinates.  This is Lean-only support for the projections in `def:cl-func`,
blueprint `blueprint/src/chapter/ch12_qpbt_games.tex:441-463`, paper origin
`references/qpbt-paper/05_conditionally_linear_functions.tex:35-57`.
-/
def coordinateRestriction (S : Finset ι) (x : ι → K) : ι → K :=
  fun i => if i ∈ S then x i else 0

/-- Evaluation of a conditionally-linear syntax term.  Lean-only support for
`def:cl-func`, blueprint `ch12_qpbt_games.tex:453-463`, paper origin
`references/qpbt-paper/05_conditionally_linear_functions.tex:35-57`.
-/
def CondLinearTerm.eval {ι : Type*} [Fintype ι] [DecidableEq ι]
    {K : Type*} [Field K] :
    {ell : ℕ} → CondLinearTerm K (ι := ι) ell → (ι → K) → (ι → K)
  | _, .zero => fun _ => 0
  | _, .succ S₁ L₁ _ rest =>
      fun x =>
        let x₁ := coordinateRestriction S₁ x
        L₁ x₁ + CondLinearTerm.eval (rest (L₁ x₁)) x

/-- The support invariant for a conditionally-linear syntax term.  This is a
Lean-only companion to `def:cl-func`, blueprint
`blueprint/src/chapter/ch12_qpbt_games.tex:453-463`, paper origin
`references/qpbt-paper/05_conditionally_linear_functions.tex:35-57`.
-/
def CondLinearTerm.supportedOn {ι : Type*} [Fintype ι] [DecidableEq ι]
    {K : Type*} [Field K] :
    {ell : ℕ} → CondLinearTerm K (ι := ι) ell → Finset ι → Prop
  | _, .zero, _ => True
  | _, .succ S₁ _ _ rest, S =>
      S₁ ⊆ S ∧ ∀ y, CondLinearTerm.supportedOn (rest y) (S \ S₁)

/-- The public conditionally-linear predicate.  Its positive syntax-tree
encoding is the Lean representation of `def:cl-func`, blueprint
`blueprint/src/chapter/ch12_qpbt_games.tex:453-463`, paper origin
`references/qpbt-paper/05_conditionally_linear_functions.tex:35-57`.
-/
def IsCondLinearOn (K : Type*) [Field K] {ι : Type*} [Fintype ι]
    [DecidableEq ι] (S : Finset ι) (ell : ℕ)
    (L : (ι → K) → (ι → K)) : Prop :=
  ∃ t : CondLinearTerm K (ι := ι) ell,
    CondLinearTerm.supportedOn t S ∧ CondLinearTerm.eval t = L

/--
`IsCondLinear` abbreviates the full-coordinate predicate.  Blueprint
`def:cl-func`, `blueprint/src/chapter/ch12_qpbt_games.tex:453-463`; paper
`references/qpbt-paper/05_conditionally_linear_functions.tex:35-57`.
-/
def IsCondLinear (ell : ℕ) (L : (ι → K) → (ι → K)) : Prop :=
  IsCondLinearOn K Finset.univ ell L

/--
The distribution obtained by applying two conditionally linear maps to a common
uniform seed.  This is `def:cl-dist` in
`blueprint/src/chapter/ch12_qpbt_games.tex:467-470`, paper origin
`references/qpbt-paper/05_conditionally_linear_functions.tex:132-138`.
-/
noncomputable def clDistribution [Fintype K] [DecidableEq K]
    (L R : (ι → K) → (ι → K)) :
    Distribution ((ι → K) × (ι → K)) :=
  (uniformDistribution (ι → K)).map (fun z => (L z, R z))

/-- The direct-sum map used to encode the paper's CL concatenation.  The left
coordinates carry `L`, while the right coordinates carry the family member
`R u v` selected by the left input `u`.  This is Lean-only coordinate
infrastructure for `lem:cl-concat`, blueprint
`blueprint/src/chapter/ch12_qpbt_games.tex:498-505`, paper origin
`references/qpbt-paper/05_conditionally_linear_functions.tex:315-364`.
-/
def condLinearConcat {ιU ιV : Type*} [Fintype ιU] [DecidableEq ιU]
    [Fintype ιV] [DecidableEq ιV] (L : (ιU → K) → (ιU → K))
    (R : (ιU → K) → (ιV → K) → (ιV → K))
    (x : ιU ⊕ ιV → K) : ιU ⊕ ιV → K :=
  let u : ιU → K := fun i => x (.inl i)
  let v : ιV → K := fun j => x (.inr j)
  Sum.elim (L u) (R u v)

/--
Concatenating an outer and an indexed inner CL map adds their levels.  This is
`lem:cl-concat` in `blueprint/src/chapter/ch12_qpbt_games.tex:498-505`, with
paper origin `references/qpbt-paper/05_conditionally_linear_functions.tex:315-364`.
The direct-sum coordinate bookkeeping is represented by `condLinearConcat`; the
level proof remains deferred in this skeleton.
-/
theorem IsCondLinearOn.concat {ιU ιV : Type*} [Fintype ιU] [DecidableEq ιU]
    [Fintype ιV] [DecidableEq ιV] {ell k : ℕ}
    {L : (ιU → K) → (ιU → K)}
    {R : (ιU → K) → (ιV → K) → (ιV → K)}
    (hL : IsCondLinearOn K (Finset.univ : Finset ιU) k L)
    (hR : ∀ u : ιU → K, u ∈ Set.range L →
      IsCondLinearOn K (Finset.univ : Finset ιV) ell (R u)) :
    IsCondLinearOn K (Finset.univ : Finset (ιU ⊕ ιV)) (k + ell)
      (condLinearConcat L R) := by
  sorry

/--
The graph distribution samples an ordered endpoint pair whose unordered edge
`s(a,b)` lies in `E`, including self-loops.  It is the inlined graph sampler of
`def:graph-distribution` in `blueprint/src/chapter/ch12_qpbt_games.tex:553-563`;
paper origin `references/qpbt-paper/08_classical_and_quantum_low_degree_tests.tex:984-1009`.
-/
noncomputable def graphDistribution {T : Type*} [Fintype T] [DecidableEq T]
    (E : Finset (Sym2 T)) : Distribution (T × T) :=
  Distribution.uniformOnFinset
    (Finset.univ.filter fun ab : T × T => Sym2.mk ab.1 ab.2 ∈ E)

/-- The graph sampler has unit mass whenever its edge set is nonempty. -/
theorem graphDistribution_isProbability {T : Type*} [Fintype T] [DecidableEq T]
    (E : Finset (Sym2 T)) (hE : E.Nonempty) :
    (graphDistribution E).IsProbability := by
  sorry

end MIPStarRE.QPBT
